version: '3.7'

x-backend: &backend
  build:
    context: .
    dockerfile: _docker/backend/Dockerfile
  image: backend
  volumes:
    - ./backend:/backend


x-frontend: &frontend
  build:
    context: .
    dockerfile: _docker/frontend/Dockerfile
  image: frontend
  volumes:
    - ./frontend:/frontend
    - ./frontend/node_modules


services:
  backend:
    <<: *backend
    command: uvicorn app.app:app --host 0.0.0.0 --port 8080 --workers 1 --log-level debug --reload
    working_dir: /backend
    expose:
      - 8080
    ports:
      - 8080:8080

  frontend:
    <<: *frontend
    command: npm run start
    ports:
      - 3000:3000
