export default {
  countries : [
    { code: 'AD', key: 'Andorra', value:"Андора",  phone: '376' },
    
    { code: 'FI', key: 'Finland', value: "Финляндия",  phone: '376' },
    { code: 'MU', key: 'Mauritius', value: "Маврикий",  phone: '376' },
    { code: 'KR', key: 'South Korea', value: "Южная Корея",  phone: '376' },
    { code: 'DK', key: 'Denmark', value: "Дания",  phone: '376' },
    { code: 'LY', key: 'Lithuania', value: "Литва",  phone: '376' },
    { code: 'AE', key: 'United Arab Emirates',   value: "ОАЭ", phone: '971' },
    { code: 'AL', key: 'Albania',   value: "Албания", phone: '355' },
    { code: 'AM', key: 'Armenia',   value: "Армения", phone: '374' },
    { code: 'AT', key: 'Austria',   value: "Австрия", phone: '43' },
    { code: 'AU', key: 'Australia', phone: '61', suggested: true },
    { code: 'AZ', key: 'Azerbaijan',   value: "Азербайджан", phone: '994' },
    { code: 'BG', key: 'Bulgaria',   value: "Болгария",
      phone: '359' },
    { code: 'BY', key: 'Belarus',   value: "Беларусь",
      phone: '375' },
    { code: 'CH', key: 'Switzerland',   value: "Швейцария", phone: '41' },
    { code: 'CN', key: 'China',   value: "Китай", phone: '86' },
    { code: 'CU', key: 'Cuba',   value: "Куба", phone: '53' },
    { code: 'CY', key: 'Cyprus',   value: "Кипр", phone: '357' },
    { code: 'CZ', key: 'Czech Republic',   value: "Чехия", phone: '420' },
    { code: 'DE', key: 'Germany',   value: "Германия", phone: '49', suggested: true },
    { code: 'DO', key: 'Dominican Republic',   value: "Доминиканская Республика", phone: '1-809' },
    { code: 'EE', key: 'Estonia',   value: "Эстония", phone: '372' },
    { code: 'ES', key: 'Spain',   value: "Испания", phone: '34' },
    { code: 'FR', key: 'France',   value: "Франция", phone: '33', suggested: true },
    { code: 'GB', key: 'United Kingdom',   value: "Великобритания", phone: '44' },
    { code: 'GE', key: 'Georgia',   value: "Грузия", phone: '995' },
    { code: 'GR', key: 'Greece',   value: "Греция", phone: '30' },
    { code: 'HR', key: 'Croatia',   value: "Хорватия", phone: '385' },
    { code: 'HU', key: 'Hungary',   value: "Венгрия", phone: '36' },
    { code: 'ID', key: 'Indonesia',   value: "Индонезия", phone: '62' },
    { code: 'IE', key: 'Ireland',   value: "Ирландия", phone: '353' },
    { code: 'IL', key: 'Israel',   value: "Израиль", phone: '972' },
    { code: 'IT', key: 'Italy',   value: "Италия", phone: '39' },
    { code: 'JO', key: 'Jordan',   value: "Иордания",phone: '962' },
    { code: 'JP', key: 'Japan',   value: "Япония", phone: '81', suggested: true },
    { code: 'LK', key: 'Sri Lanka',   value: "Шри-Ланка", phone: '94' },
    { code: 'LV', key: 'Latvia',   value: "Латвия", phone: '371' },
    { code: 'ME', key: 'Montenegro',   value: "Черногория", phone: '382' },
    { code: 'MV', key: 'Maldives',   value: "Мальдивы", phone: '960' },
    { code: 'MX', key: 'Mexico',   value: "Мексика", phone: '52' },
    { code: 'NO', key: 'Norway',   value: "Норвегия", phone: '47' },
    { code: 'PL', key: 'Poland',   value: "Польша", phone: '48' },
    { code: 'PT', key: 'Portugal',   value: "Португалия", phone: '351' },
    { code: 'RS', key: 'Serbia',   value: "Сербия", phone: '381' },
    { code: 'RU', key: 'Russian Federation',   value: "Россия", phone: '7' },
    { code: 'SE', key: 'Sweden',   value: "Швеция", phone: '46' },
    { code: 'SI', key: 'Slovenia',   value: "Словения", phone: '386' },
    { code: 'TH', key: 'Thailand',   value: "Таиланд", phone: '66' },
    { code: 'TN', key: 'Tunisia',   value: "Тунис", phone: '216' },
    { code: 'TR', key: 'Turkey',  value: "Турция", phone: '90' },
    { code: 'VN', key: 'Vietnam',   value: "Вьетнам", phone: '84' },
    { code: 'AB', key: 'Abkhazia',   value: "Абхазия", phone: '376' },
    { code: '', key: 'Cruises', value: "Круизы",  phone: '376' },
  ],
}
